sudo: required
services: 
  -docker

before_install:
  - docker build -t vbakalov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vbakalov/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-106601051625"
  bucket_path: "dockerreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
   
